//! Gridlet engine — enumerates crossword-style grids from a list of words.
//!
//! Strategy (per the product directives):
//!   * every word is tried as the starting *pivot*, placed horizontally;
//!   * all crossings via shared letters are generated by backtracking;
//!   * letter conflicts (one cell = one letter) are rejected;
//!   * words glued end-to-end (touching first/last letters) are rejected;
//!   * a configurable minimum gap keeps parallel words apart.
//!
//! The result is a deduplicated list of grids. Aesthetic sorting (compactness,
//! balance, centering, …) is done on the JavaScript side, which has the whole
//! set available for normalization.

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use wasm_bindgen::prelude::*;

// ---------------------------------------------------------------------------
// Public input / output types
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Deserialize)]
#[serde(rename_all = "lowercase")]
enum WordDir {
    Horizontal,
    Vertical,
    Both,
}

fn default_word_dir() -> WordDir {
    WordDir::Both
}
fn default_gap() -> i32 {
    1
}

#[derive(Deserialize)]
struct WordSpec {
    text: String,
    /// Allowed orientation(s) for this specific word.
    #[serde(default = "default_word_dir")]
    direction: WordDir,
}

#[derive(Deserialize)]
struct GenerateInput {
    words: Vec<WordSpec>,
    /// Minimum number of empty cells required between two parallel words (0–5).
    #[serde(default = "default_gap")]
    gap: i32,
}

#[derive(Serialize)]
struct CellOut {
    row: i32,
    col: i32,
    ch: String,
    crossing: bool,
}

#[derive(Serialize)]
struct GridOut {
    rows: i32,
    cols: i32,
    crossings: i32,
    letters: i32,
    words: i32, // number of input words actually placed in this grid
    cells: Vec<CellOut>,
}

#[derive(Serialize)]
struct Output {
    grids: Vec<GridOut>,
    count: usize,
    pivots_tested: usize,
    truncated: bool,
}

// ---------------------------------------------------------------------------
// Internal model
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq)]
enum Dir {
    H,
    V,
}
impl Dir {
    fn step(self) -> (i32, i32) {
        match self {
            Dir::H => (0, 1),
            Dir::V => (1, 0),
        }
    }
}

struct WordItem {
    norm: Vec<char>,    // accent-folded uppercase, for matching
    disp: Vec<char>,    // uppercased original, for display
    dirs: Vec<Dir>,     // orientations this word is allowed to take
}

#[derive(Clone)]
struct CellState {
    ch: char,
    h: bool,
    v: bool,
}

struct Undo {
    inserted: Vec<(i32, i32)>,
    flagged: Vec<(i32, i32)>,
    dir: Dir,
}

// ---------------------------------------------------------------------------
// Character normalization
// ---------------------------------------------------------------------------

fn normalize_char(c: char) -> char {
    let lc = c.to_lowercase().next().unwrap_or(c);
    let folded = match lc {
        'à' | 'á' | 'â' | 'ã' | 'ä' | 'å' => 'a',
        'é' | 'è' | 'ê' | 'ë' => 'e',
        'í' | 'ì' | 'î' | 'ï' => 'i',
        'ó' | 'ò' | 'ô' | 'õ' | 'ö' => 'o',
        'ú' | 'ù' | 'û' | 'ü' => 'u',
        'ç' => 'c',
        'ñ' => 'n',
        'ÿ' | 'ý' => 'y',
        other => other,
    };
    folded.to_ascii_uppercase()
}
fn disp_char(c: char) -> char {
    c.to_uppercase().next().unwrap_or(c)
}

// ---------------------------------------------------------------------------
// Search engine
// ---------------------------------------------------------------------------

const MAX_GRIDS: usize = 400;
const NODE_BUDGET: i64 = 600_000;

struct Engine<'a> {
    items: &'a [WordItem],
    gap: i32,
    cells: HashMap<(i32, i32), CellState>,
    sigs: HashSet<String>,
    results: Vec<GridOut>,
    best_count: usize,
    budget: i64,
    truncated: bool,
}

impl<'a> Engine<'a> {
    fn done(&self) -> bool {
        self.results.len() >= MAX_GRIDS || self.budget <= 0
    }

    /// Check whether `word` fits at (row, col) running in `dir`.
    /// Returns the number of crossings, or `None` if the placement is invalid.
    fn check(&self, word: &WordItem, row: i32, col: i32, dir: Dir) -> Option<i32> {
        let (dr, dc) = dir.step();
        let n = word.norm.len() as i32;

        // Anti-glue: cells immediately before/after the word must be empty.
        if self.cells.contains_key(&(row - dr, col - dc)) {
            return None;
        }
        if self.cells.contains_key(&(row + dr * n, col + dc * n)) {
            return None;
        }

        let mut crossings = 0;
        for i in 0..n {
            let coord = (row + dr * i, col + dc * i);
            match self.cells.get(&coord) {
                Some(cell) => {
                    // One cell = one letter.
                    if normalize_char(cell.ch) != word.norm[i as usize] {
                        return None;
                    }
                    // Only perpendicular crossings allowed (no parallel overlap).
                    let parallel = match dir {
                        Dir::H => cell.h,
                        Dir::V => cell.v,
                    };
                    if parallel {
                        return None;
                    }
                    crossings += 1;
                }
                None => {
                    // Keep parallel words at least `gap` empty cells apart.
                    for d in 1..=self.gap {
                        let (p1, p2) = match dir {
                            Dir::H => ((coord.0 - d, coord.1), (coord.0 + d, coord.1)),
                            Dir::V => ((coord.0, coord.1 - d), (coord.0, coord.1 + d)),
                        };
                        if self.cells.contains_key(&p1) || self.cells.contains_key(&p2) {
                            return None;
                        }
                    }
                }
            }
        }

        // Every word but the pivot must cross the existing structure.
        if !self.cells.is_empty() && crossings == 0 {
            return None;
        }
        Some(crossings)
    }

    fn place(&mut self, word: &WordItem, row: i32, col: i32, dir: Dir) -> Undo {
        let (dr, dc) = dir.step();
        let mut undo = Undo { inserted: vec![], flagged: vec![], dir };
        for i in 0..word.disp.len() as i32 {
            let coord = (row + dr * i, col + dc * i);
            match self.cells.get_mut(&coord) {
                Some(cell) => {
                    match dir {
                        Dir::H => cell.h = true,
                        Dir::V => cell.v = true,
                    }
                    undo.flagged.push(coord);
                }
                None => {
                    self.cells.insert(
                        coord,
                        CellState {
                            ch: word.disp[i as usize],
                            h: dir == Dir::H,
                            v: dir == Dir::V,
                        },
                    );
                    undo.inserted.push(coord);
                }
            }
        }
        undo
    }

    fn unplace(&mut self, undo: Undo) {
        for coord in undo.inserted {
            self.cells.remove(&coord);
        }
        for coord in undo.flagged {
            if let Some(cell) = self.cells.get_mut(&coord) {
                match undo.dir {
                    Dir::H => cell.h = false,
                    Dir::V => cell.v = false,
                }
            }
        }
    }

    /// All valid placements of `word` against the current (non-empty) grid.
    fn candidates(&self, word: &WordItem) -> Vec<(i32, i32, Dir)> {
        let mut out = Vec::new();
        let mut seen: HashSet<(i32, i32, u8)> = HashSet::new();
        for (i, &ch) in word.norm.iter().enumerate() {
            for (&coord, cell) in &self.cells {
                if normalize_char(cell.ch) != ch {
                    continue;
                }
                for &dir in &word.dirs {
                    let (dr, dc) = dir.step();
                    let row = coord.0 - dr * i as i32;
                    let col = coord.1 - dc * i as i32;
                    let key = (row, col, if dir == Dir::H { 0 } else { 1 });
                    if !seen.insert(key) {
                        continue;
                    }
                    if self.check(word, row, col, dir).is_some() {
                        out.push((row, col, dir));
                    }
                }
            }
        }
        out
    }

    /// Backtracking: at each step place the connectable word with the fewest
    /// candidates (MRV), branching on all its placements.
    fn solve(&mut self, remaining: &[usize]) {
        if self.done() {
            return;
        }
        self.budget -= 1;

        if remaining.is_empty() {
            self.record(self.items.len());
            return;
        }

        // Pick the connectable word (>=1 candidate) with the fewest options.
        let mut chosen: Option<(usize, Vec<(i32, i32, Dir)>)> = None;
        for (pos, &wi) in remaining.iter().enumerate() {
            let cands = self.candidates(&self.items[wi]);
            if cands.is_empty() {
                continue;
            }
            let better = match &chosen {
                None => true,
                Some((_, c)) => cands.len() < c.len(),
            };
            if better {
                chosen = Some((pos, cands));
            }
        }

        let (pos, cands) = match chosen {
            // No remaining word connects: record the best-effort partial grid.
            None => {
                self.record(self.items.len() - remaining.len());
                return;
            }
            Some(v) => v,
        };

        let word_idx = remaining[pos];
        let mut rest: Vec<usize> = Vec::with_capacity(remaining.len() - 1);
        rest.extend_from_slice(&remaining[..pos]);
        rest.extend_from_slice(&remaining[pos + 1..]);

        for (row, col, dir) in cands {
            let undo = self.place(&self.items[word_idx], row, col, dir);
            self.solve(&rest);
            self.unplace(undo);
            if self.done() {
                return;
            }
        }
    }

    fn record(&mut self, placed_count: usize) {
        // Keep only the grids with the highest word coverage seen so far.
        if placed_count < self.best_count {
            return;
        }
        if placed_count > self.best_count {
            self.best_count = placed_count;
            self.results.clear();
            self.sigs.clear();
        }

        let (min_r, max_r, min_c, max_c) = self.cells.keys().fold(
            (i32::MAX, i32::MIN, i32::MAX, i32::MIN),
            |(a, b, c, d), &(r, cc)| (a.min(r), b.max(r), c.min(cc), d.max(cc)),
        );

        // Signature for deduplication (normalized coords + folded letter).
        let mut sig_parts: Vec<(i32, i32, char)> = self
            .cells
            .iter()
            .map(|(&(r, c), cell)| (r - min_r, c - min_c, normalize_char(cell.ch)))
            .collect();
        sig_parts.sort_unstable();
        let mut sig = String::with_capacity(sig_parts.len() * 6);
        for (r, c, ch) in &sig_parts {
            sig.push_str(&format!("{},{},{};", r, c, ch));
        }
        if !self.sigs.insert(sig) {
            return; // duplicate grid
        }

        let mut crossings = 0;
        let cells: Vec<CellOut> = self
            .cells
            .iter()
            .map(|(&(r, c), cell)| {
                let cross = cell.h && cell.v;
                if cross {
                    crossings += 1;
                }
                CellOut {
                    row: r - min_r,
                    col: c - min_c,
                    ch: cell.ch.to_string(),
                    crossing: cross,
                }
            })
            .collect();

        self.results.push(GridOut {
            rows: max_r - min_r + 1,
            cols: max_c - min_c + 1,
            crossings,
            letters: cells.len() as i32,
            words: placed_count as i32,
            cells,
        });

        if self.results.len() >= MAX_GRIDS {
            self.truncated = true;
        }
    }
}

fn run(input: GenerateInput) -> Output {
    let items: Vec<WordItem> = input
        .words
        .iter()
        .filter_map(|w| {
            let t = w.text.trim();
            let norm: Vec<char> = t.chars().map(normalize_char).collect();
            if norm.is_empty() {
                return None;
            }
            let dirs = match w.direction {
                WordDir::Horizontal => vec![Dir::H],
                WordDir::Vertical => vec![Dir::V],
                WordDir::Both => vec![Dir::H, Dir::V],
            };
            Some(WordItem {
                disp: t.chars().map(disp_char).collect(),
                norm,
                dirs,
            })
        })
        .collect();

    let n = items.len();
    if n == 0 {
        return Output { grids: vec![], count: 0, pivots_tested: 0, truncated: false };
    }

    let mut engine = Engine {
        items: &items,
        gap: input.gap.clamp(0, 5),
        cells: HashMap::new(),
        sigs: HashSet::new(),
        results: Vec::new(),
        best_count: 0,
        budget: NODE_BUDGET,
        truncated: false,
    };

    let mut pivots_tested = 0;
    for p in 0..n {
        if engine.done() {
            break;
        }
        pivots_tested += 1;
        // Pivot laid out horizontally when the word allows it, else vertically.
        let pivot_dir = if items[p].dirs.contains(&Dir::H) { Dir::H } else { Dir::V };
        let undo = engine.place(&items[p], 0, 0, pivot_dir);
        let remaining: Vec<usize> = (0..n).filter(|&i| i != p).collect();
        engine.solve(&remaining);
        engine.unplace(undo);
    }

    Output {
        count: engine.results.len(),
        truncated: engine.truncated,
        pivots_tested,
        grids: engine.results,
    }
}

/// Generate crossword grids. `input` matches `GenerateInput`; the result matches
/// `Output`.
#[wasm_bindgen]
pub fn generate_grid(input: JsValue) -> Result<JsValue, JsValue> {
    let parsed: GenerateInput =
        serde_wasm_bindgen::from_value(input).map_err(|e| JsValue::from_str(&e.to_string()))?;
    let result = run(parsed);
    serde_wasm_bindgen::to_value(&result).map_err(|e| JsValue::from_str(&e.to_string()))
}

// ---------------------------------------------------------------------------
// Native tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn input(words: &[&str], direction: WordDir, gap: i32) -> GenerateInput {
        GenerateInput {
            words: words
                .iter()
                .map(|s| WordSpec { text: s.to_string(), direction })
                .collect(),
            gap,
        }
    }

    fn render(g: &GridOut) -> String {
        let mut map: HashMap<(i32, i32), String> = HashMap::new();
        for c in &g.cells {
            map.insert((c.row, c.col), c.ch.clone());
        }
        let mut out = String::new();
        for r in 0..g.rows {
            for c in 0..g.cols {
                out.push_str(map.get(&(r, c)).map(|s| s.as_str()).unwrap_or("."));
            }
            out.push('\n');
        }
        out
    }

    /// Each placed word must read correctly off the rendered grid.
    fn assert_no_conflicts(g: &GridOut) {
        let mut map: HashMap<(i32, i32), char> = HashMap::new();
        for c in &g.cells {
            let ch = c.ch.chars().next().unwrap();
            if let Some(&prev) = map.get(&(c.row, c.col)) {
                assert_eq!(normalize_char(prev), normalize_char(ch), "cell conflict");
            }
            map.insert((c.row, c.col), ch);
        }
    }

    #[test]
    fn enumerates_multiple_distinct_grids() {
        let out = run(input(&["Paul", "Camille", "Arthur"], WordDir::Both, 1));
        println!("\n{} grids, sample:\n{}", out.count, render(&out.grids[0]));
        assert!(out.count >= 2, "expected several grids, got {}", out.count);
        for g in &out.grids {
            assert_eq!(g.letters, g.cells.len() as i32);
            assert!(g.crossings >= 1);
            assert_no_conflicts(g);
        }
        // All three words placed -> at least 3 distinct letters' worth of rows/cols.
        assert!(out.grids.iter().all(|g| g.letters >= 7));
    }

    #[test]
    fn grids_are_deduplicated() {
        let out = run(input(&["Paul", "Camille", "Arthur"], WordDir::Both, 1));
        let mut seen = HashSet::new();
        for g in &out.grids {
            let mut key: Vec<(i32, i32, String)> =
                g.cells.iter().map(|c| (c.row, c.col, c.ch.clone())).collect();
            key.sort();
            assert!(seen.insert(key), "duplicate grid found");
        }
    }

    #[test]
    fn larger_gap_reduces_or_keeps_solutions() {
        let tight = run(input(&["Paul", "Camille", "Arthur", "Marie"], WordDir::Both, 1));
        let loose = run(input(&["Paul", "Camille", "Arthur", "Marie"], WordDir::Both, 4));
        assert!(loose.count <= tight.count, "more spacing should not add grids");
    }

    #[test]
    fn horizontal_only_cannot_cross() {
        let out = run(input(&["Paul", "Arthur"], WordDir::Horizontal, 1));
        // No crossing possible -> best coverage is a single word, no crossings.
        for g in &out.grids {
            assert_eq!(g.crossings, 0);
        }
    }

    #[test]
    fn places_the_seven_name_list_in_full() {
        // The exact list the user reported as sometimes incomplete.
        let out = run(input(
            &["Etienne", "Odile", "Bertrand", "Louis", "Thomas", "Marie-Claire", "Paul"],
            WordDir::Both,
            1,
        ));
        assert!(out.count >= 1, "no grid produced");
        println!("\n{} grids, words placed = {}\n{}", out.count, out.grids[0].words, render(&out.grids[0]));
        // The best grids must place all seven words.
        assert_eq!(out.grids[0].words, 7, "best grid does not place all 7 words");
        for g in &out.grids {
            assert_eq!(g.words, 7);
            assert_no_conflicts(g);
        }
    }

    #[test]
    fn per_word_direction_is_respected() {
        // Camille forced vertical, Paul forced horizontal; they must cross.
        let inp = GenerateInput {
            words: vec![
                WordSpec { text: "Paul".into(), direction: WordDir::Horizontal },
                WordSpec { text: "Camille".into(), direction: WordDir::Vertical },
            ],
            gap: 1,
        };
        let out = run(inp);
        assert!(out.count >= 1);
        assert!(out.grids.iter().all(|g| g.words == 2 && g.crossings >= 1));
    }

    #[test]
    fn words_field_matches_input_count() {
        let out = run(input(&["Paul", "Camille", "Arthur"], WordDir::Both, 1));
        assert!(out.grids.iter().all(|g| g.words == 3));
    }
}
